language: bash
services:
- docker
sudo: required
branches:
  only:
  - master
script:
- docker build . -t "mikeyboom/attendance:latest"
after_success:
- docker login --username=$dockername -p="$dockerpassword" dockerhub
- docker push mikeyboom/dockerhub:latest
- chmod 600 id_rsa
- scp -o "StrictHostKeyChecking no" -i id_rsa docker-compose.yml root@$ip:/home/mikey/Attendance/
- ssh -o "StrictHostKeyChecking no" -i id_rsa root@$ip "cd /home/mikey/Attendance/;sudo
  docker-compose -f docker-compose.yml pull;sudo docker-compose -f docker-compose.yml
  up -d;exit"
before_install:
- openssl aes-256-cbc -K $encrypted_71a1e6d76d99_key -iv $encrypted_71a1e6d76d99_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
